version: '3'
services:
  db:
    image: mysql:5.7.16
    restart: always
    environment:
      MYSQL_DATABASE: calorina
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 3000:3306
  backend:
    build: .
    volumes:
      - .:/app
    ports:
      - 1234:8000
    depends_on:
      - db

