# Generated by Django 4.1 on 2024-01-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('calories', models.DecimalField(decimal_places=2, max_digits=5)),
                ('serving_size', models.DecimalField(decimal_places=3, max_digits=6)),
                ('fiber', models.DecimalField(decimal_places=3, max_digits=6)),
                ('protein', models.DecimalField(decimal_places=3, max_digits=6)),
                ('carbohydrates', models.DecimalField(decimal_places=3, max_digits=6)),
                ('total_fat', models.DecimalField(decimal_places=3, max_digits=6)),
                ('saturated_fat', models.DecimalField(decimal_places=3, max_digits=6)),
                ('trans_fat', models.DecimalField(decimal_places=3, max_digits=6)),
                ('cholesterol', models.DecimalField(decimal_places=3, max_digits=6)),
                ('sodium', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
        ),
    ]
